### PR TITLE
add notfy workflow

### PR DESCRIPTION
**Pull request by Prateeknandle**

### CODE REVIEW

**Comment by Prateeknandle** [comment]
@nywilken  does this looks good?

**Review by nywilken — APPROVED** [review]
@Prateeknandle these additions look good to me. Once added you should be able to trigger a documentation ingestion job using the manual integration release action. The version for your plug looks to be 0.0.1 still. You may want to see about bumping that if you have new changes. 

That aside the .goreleaser.yml file has a step for generating a docs.zip file which is no longer needed. The following line can be removed https://github.com/kubearmor/packer-plugin-kubearmor/blob/1a95c3388e30f37d16d846c4ed32c7d1e6bf05e5/.goreleaser.yml#L12

**Comment by Prateeknandle** [comment]
> you should be able to trigger a documentation ingestion job using the manual integration release action

@nywilken do you mean creating a release or run workflow [here](https://github.com/kubearmor/packer-plugin-kubearmor/actions/workflows/notify-integration-release-via-manual.yaml)?
if need to create a release then I'll remove the existing one and create a new one with the same tag, I've changed the tag in the changes from `1.0.0` to `0.0.1`

**Comment by nywilken** [comment]
Yes @Prateeknandle you can trigger a manual workflow using https://github.com/kubearmor/packer-plugin-kubearmor/blob/main/.github/workflows/notify-integration-release-via-manual.yaml

**Comment by Prateeknandle** [comment]
@nywilken [https://github.com/kubearmor/packer-plugin-kubearmor/actions/runs/8296182970](https://github.com/kubearmor/packer-plugin-kubearmor/actions/runs/8296182970) the manual workflow is complete.

**Comment by Prateeknandle** [comment]
@nywilken what's next now?

**Comment by nywilken** [comment]
Hi @Prateeknandle the docs are live but the format is not right https://developer.hashicorp.com/packer/integrations/kubearmor/kubearmor and the link to provisioner is broken.

**Comment by Prateeknandle** [comment]
@nywilken to update documentation I've to run the workflow again?

**Comment by nywilken** [comment]
> @nywilken to update the documentation do I've to run the workflow again?

Yes, that will trigger an update.

**Comment by Prateeknandle** [comment]
@nywilken can you please check [https://developer.hashicorp.com/packer/integrations/kubearmor/kubearmor](https://developer.hashicorp.com/packer/integrations/kubearmor/kubearmor) and let me know if anything needs to be fixed, I've fixed the broken link and structure issue.

**Pull request merged**
